### ISSUE TITLE
@koa/router vs koa-router confusion

### ISSUE THREAD

**Issue by linde12** [koajs/router#109]
Hi.

I'm trying out Koa and i wanted to get started with a simple crud app with a couple of routes but quickly ran into problems. There is a package on npm, `@koa/router`, which is under koajs/router here on Github, but there is also a package called `koa-router` with 4.7k stars on github which looks to be the same thing. However when installing types with `npm i @types/koa-router` the declarations only work if i use `koa-router` and not `@koa/router`

So the question is: which package is the "official" one, and does it also have typescript definitions (& if so how do i use/install them)? This is _very_ confusing and unfortunately also very off-putting to someone new to the ecosystem, so i'm curious to why or if im doing something very wrong.

#### Expected Behavior:

`@types/koa-router` to work for `@koa/router`

#### Actual Behavior:

`@types/koa-router` works for the (3rd party?) package `koa-router`

**Comment by dominicegginton** [comment]
Hi @linde12 

This module is forked from the original koa-router due to its lack of activity, and this repository is now the official version. Install with `npm i @koa/router`. I would be nice to have all the official **Koa** modules be published to the npm registry under the **Koa** scope as this would make it easier for newcomers like yourself.

To address your typescript issues try [**@tpes/koa__router**](https://www.npmjs.com/package/@types/koa__router). I believe this package contains the type definitions you are looking for. Haven't used typescript myself so haven't tried it myself sorry.

Hope this helps 😄

**Comment by linde12** [comment]
> Hi @linde12
> 
> This module is forked from the original koa-router due to its lack of activity, and this repository is now the official version. Install with `npm i @koa/router`. I would be nice to have all the official **Koa** modules be published to the npm registry under the **Koa** scope as this would make it easier for newcomers like yourself.
> 
> To address your typescript issues try [**@tpes/koa__router**](https://www.npmjs.com/package/@types/koa__router). I believe this package contains the type definitions you are looking for. Haven't used typescript myself so haven't tried it myself sorry.
> 
> Hope this helps 😄

Ah, i see! I will try the @types/koa__router package. Closing the issue, thank you!
