### ISSUE TITLE
Route callback from a controller class

### ISSUE THREAD

**Issue by kukukk** [koajs/router#125]
I'm working on defining my controllers in separate classes, but I encountered a strange situation (at least for me it is :}). It probably is not koa-router related, but I hope that somebody can explain why is this happening.

node.js version: v14.16.0
npm version: 7.19.1
`@koa/router` version: 10.1.0
`koa` version: 2.13.1

#### Code sample:

```js
import Router from '@koa/router';
import Koa, { Context } from 'koa';

class MyController {
  public async test(ctx: Context) {
    console.log(this);
    ctx.status = 200;
    ctx.body = { message: 'Hello world' };
  }
}
const myController = new MyController();

const router = new Router();
router.get('/api1', (ctx) => myController.test(ctx));
router.get('/api2', myController.test);

const app: Koa = new Koa();
app.use(router.routes());
app.use(router.allowedMethods());
app.listen(3000, () => {
  console.log('Listening on port 3000');
});

export default app;
```

#### Expected Behavior:

I expect to see in the logs `MyController {}` when calling `/api1` and `/api2`

#### Actual Behavior:

I see in the logs `undefined` when I call `/api2`

**Comment by dominicegginton** [comment]
Thanks for opening an issue. You are right this is not related to **koa-router**, but I believe I can help. You are experiencing this because you are using the async function called `test()` as a high order function (passed as an argument). When you pass a high order function you will not be able to access *this* as it will be undefined. You see the expected result when you send a request to the **/api1** endpoint as you not passing the function as a parameter to the `router.get()` function.

You may find this [MDN](https://developer.mozilla.org/en-US/docs/Glossary/First-class_Function) documentation helpful.

**Comment by kukukk** [comment]
Thank you for pointing me to the right direction.
