### ISSUE TITLE
[fix] ctx.request.body 不能设置类型标注

### ISSUE THREAD

**Issue by wuxu1230** [koajs/router#177]
为何只有 body 不能设置类型，难道只能使用
`request.body as {...}` 方式吗，希望解决下面的使用出现的类型丢失问题
![image](https://github.com/koajs/router/assets/46241389/9b4e6527-16ba-42a6-a733-953a6fee01b7)

源代码如下（"@types/koa": "2.13.10", "@types/koa__router": "12.0.3"）
``` typescript
import Router from "@koa/router"
const router = new Router()
interface KoaState {
    a: string
}
interface Context {
    request: {
        params: {
            id: string
        }
        body: {
            c: string
        }
        body2: {
            d: string
        }
    }
}
interface ResponseBody {
    b: string
}

router.post<KoaState, Context, ResponseBody>("/:id", async (ctx) => {
    const {state, request, response} = ctx
    const a = state.a
    const id = request.params.id
    const c = request.body.c
    const d = request.body2.d
    const b = response.body.b
})
```

**Comment by 3imed-jaberi** [comment]
@wuxu1230 I apologize if I misunderstood due to using a translator (I don't know Chinese).

It seems the issue is related to the types repository. You can open an issue there for further assistance. Alternatively, you can try updating to the latest versions of the packages: `"@types/koa": "^2.15.0"` and `"@types/koa__router": "^12.0.4"`.
