### ISSUE TITLE
Add a TypeScript integration doc

### ISSUE THREAD

**Issue by brunoti** [koajs/router#78]
Hi!

Can we have a TypeScript integration doc add to the project? I had a hard time trying to understand why my code was not compiling because of @types/koa-router vs @types/koa__router [and this issue I found on StackOverflow](https://stackoverflow.com/questions/56125831/how-to-invoke-a-controller-method-from-koa-router).

I believe that other people had the same problem, and I saw on some issues that you don't really want to support TS and that's ok. But can I add a simple .md doc for TypeScript integration and reference it on the readme?

Thanks for the great package, you are awesome!

**Comment by niftylettuce** [comment]
I do not support nor encourage TypeScript to be used in the JavaScript open source community.

**Comment by zacanger** [comment]
@brunoti that's an issue with all scoped packages that have types under the `@types` scope, not really a Koa Router issue. Every `@types/` package for something that's already under a scope uses a double underscore to refer to a package in another scope. https://github.com/DefinitelyTyped/DefinitelyTyped/tree/987a09b4979415a83491328a57cf4def5b7e1bc7#what-about-scoped-packages

**Comment by aaomidi** [comment]
Annnnnd just like that I'm back to express. Thanks @niftylettuce

**Comment by niftylettuce** [comment]
Even Ryah Dahl, the author of Node.js and author of Deno has abandoned TypeScript.

And I got your message @aaomidi.  I hope your switch back to Express works for you.  I'm a former Express TC member and help to push the community forwards off legacy and bloat.

![Screen Shot 2020-06-23 at 5 04 46 AM](https://user-images.githubusercontent.com/523141/85391015-41206380-b50f-11ea-88e1-40cebc80a4bd.png)

I have nothing against the authors of TypeScript, but it is convoluted unnecessary bloat.  It is against our principles and I will never support it.  It will _only_ ever slow you down.

https://lad.js.org/#/?id=principles

Look at some amazing work I've shipped since January that DOES not use TypeScript and does use Koa, Koa Router, etc = https://github.com/forwardemail/forwardemail.net.
