### ISSUE TITLE
Core breaking issues with v9.x

### ISSUE THREAD

**Issue by niftylettuce** [koajs/router#79]
I'm not sure what's up here @Sinewyk @zacanger but I upgraded a project to v9.x and it broke authentication (Google auth passport).

Just filing this for now until I can figure it out.

**Comment by niftylettuce** [comment]
I deprecated v9.0.0 as I found core issues with it in my app

**Comment by Sinewyk** [comment]
Thoughts:
 - It is a breaking change. Anyone using `^` (which is the default in all package managers afaik) should not have any issues UNLESS they specifically ask for a major upgrade (cf, read their accompanying package manager documentation). No need to lock things down, it's already the case.
 - I'm interested in more information. All tests are green, and I actually don't see `@koa/router` being used in your automatically linked package other than in a test.

**Comment by zacanger** [comment]
Do you have a code sample? I just tried a super minimal test with koa-passport and the local strategy, and didn't have any problems.

**Comment by niftylettuce** [comment]
Yes, auth is broken on https://github.com/ladjs/lad.sh for Google Sign In.
Not 100% sure why.  I have unpublished v9.0.0 completely from npm with
their help as well until this is further resolved.

**Comment by lagden** [comment]
:(
I'm using v9.0.0!

**Comment by zacanger** [comment]
Unpublishing was probably a risky choice, that could break builds. I just had to run through six microservices and downgrade real quick.

**Comment by niftylettuce** [comment]
I only had published v9.0.0 to `@koa/router` (I did not mirror it to `koa-router`).  If you want to keep using v9.0.0 you can install via:

```sh
npm install https://github.com/koajs/router#v9.0.0
```

or with yarn:

```sh
yarn add https://github.com/koajs/router#v9.0.0
```

**Comment by niftylettuce** [comment]
Or we can try to figure out what the underling issue is here - I believe it to be something with `/foo/:param/bar` personally.

**Comment by Sinewyk** [comment]
Major changes that could trip people up with the underlying `path-to-regexp` change:
  - encode/decode stuff, if you used to just pass shit in the url, now you have to specify encode/decode when generating links <= I fixed the tests to use encode/decode, but no note in the readme.
  - No more wildcard `*`, use the other syntax <= we had no test for this, but we added a note in the readme.
  - They removed automatic `/stuff/` ending slash removal, so there's a special behavior when prefixing and trying to add a route on `'/'` in koa-router if we did not specify strict. <= there's a test for this one.

**Comment by rynti** [comment]
I don't understand why the version was unpublished.
Version 9 introduced breaking changes, which means that users of the library potentially have to implement changes to keep their code working with the new version - which is what I had to do. But this should not be a surprise as the usage of semantic versioning (pushing a new major version) makes this apparent.
Nonetheless, thanks for providing the alternative route with installing the release via the GitHub URL which serves as a quick fix in my case.

**Comment by zacanger** [comment]
@niftylettuce could the trailing slash thing be the issue, if you have any routes that end in a slash? Here's a test with v9:

```javascript
const Koa = require('koa')
const Router = require('@koa/router')

const app = new Koa()
const router = new Router()

// curl foo/whatever/baz -> whatever
// curl foo/whatever/baz/ -> whatever
router.get('/foo/:bar/baz', (ctx) => {
  ctx.body = ctx.params.bar
})

// curl foo/whatever/quux/ -> whatever
// curl foo/whatever/quux (no slash) -> 404
router.get('/foo/:bar/quux/', (ctx) => {
  ctx.body = ctx.params.bar
})

app.use(router.routes())
app.listen(9999)
```

**Comment by ohardy** [comment]
Hi,

Really, you can't unpublish a package published more than 10 days ago !! Everything are stuck on our side because of that.

Can you publish again this version and handle fixes in a 9.0.1 plz ?

Thanks

**Comment by JacobMGEvans** [comment]
> @niftylettuce could the trailing slash thing be the issue, if you have any routes that end in a slash? Here's a test I just did with v9:
> 
> ```js
> const Koa = require('koa')
> const Router = require('@koa/router')
> 
> const app = new Koa()
> const router = new Router()
> 
> // GET foo/whatever/baz -> whatever
> // GET foo/whatever/baz/ -> whatever
> router.get('/foo/:bar/baz', (ctx) => {
>   ctx.body = ctx.params.bar
> })
> 
> // GET foo/whatever/quux/ -> whatever
> // GET foo/whatever/quux (no slash) -> 404
> router.get('/foo/:bar/quux/', (ctx) => {
>   ctx.body = ctx.params.bar
> })
> 
> app.use(router.routes())
> app.listen(9999)
> ```
> 
> Which differs from v8, in v8 none of the requests resulted in a 404.

It would be a great test case to add too and include the Tests in the Travis build, which might catch future issues.

**Comment by zjr** [comment]
> No more wildcard *, use the other syntax <= we had no test for this, but we added a note in the readme

@Sinewyk Where is there a note about this in the readme? I looked in the README.md, in the API reference, and in the release notes all on v9.0.0 and don't see anything.

When I saw the major version change I checked all over for notes about what might be breaking changes and didn't see anything referencing this.

**Comment by zacanger** [comment]
@zjr Not in the readme, it's in the changelog, `history.md`

**Comment by zjr** [comment]
Ahhhhh thank you @zacanger. I didn't even see that since I'm used to looking for a CHANGELOG.md. Any particular reason that kind of stuff doesn't go into the release notes? 

Here's where this is weird for me, and I mention it because maybe it's weird for other people too…

I have several different projects in maintenance that use this dependency. Since I can't manually go around checking deps everyday I automate it with Dependabot (this is the GH-blessed dep updator, probably there are others that do the same thing, this is the one I know). As far as I know, this pulls information from your release notes and a CHANGELOG.md. I don't know how standard CHANGELOG.md is vs. history.md and I don't mean to suggest that you alter anything for my particular preferences in that regard. What _would_ be awesome is, if you're using GH releases, to please please please put breaking changes in the release notes. When you have release notes, and they are generally somewhat informative, it's very easy for someone such as myself to make the assumption that they have all the information they should need about what is being changed and what is breaking.

**Comment by zjr** [comment]
There's a small bit of extra weirdness with this repository in particular in that you've had other major revisions that didn't necessarily reflect any actual breaking changes due to that whole kerfuffle about splitting this codebase away from the other repo that got sold etc etc.

**Comment by zacanger** [comment]
It looks like dependabot does support `history.md`: https://github.com/dependabot/dependabot-core/blob/d5240b0e22cce76a52041dd88258a923db1a176c/common/lib/dependabot/metadata_finders/base/changelog_finder.rb#L20

I agree that keeping all release notes under GH releases would be good. That was probably my bad, rather than submitting https://github.com/koajs/router/pull/77 I should've asked for the release notes in the releases tab to be updated.

**Comment by zjr** [comment]
That does appear like it should support them. I think I see what the problem is (was).

The 9.0.0 release was made April 8th, but the history.md wasn't updated until April 14th. So, nothing would have gotten picked up and this wouldn't have been available on release. At least assuming I'm reading everything correctly. I'm looking at the date on the release and the merge date on the PR you linked (#77). Ah and yeah, now that I'm looking at the original issue (#76) it definitely looks like this just wasn't mentioned anywhere. So I definitely wouldn't say this is your fault @zacanger. Updating the releases tab after your issue wouldn't have made a difference to anybody who was trying to decide whether or not they could upgrade this dependency when the release was made.

**Comment by niftylettuce** [comment]
If anyone wants to submit a PR with more test cases added, and if any break, patches, please do.  Thank you
